### ISSUE TITLE
《Web 开发简史与运行机制 》章节引用申请

### ISSUE THREAD

**Issue by xiaosansiji** [wxyyxc1992/Web-Series#13]
Hi，王下兄你好，我在我的一篇[文章](https://github.com/xiaosansiji/cookbook-of-webdev/blob/master/front-end-history/front-end-history.md#%E5%89%8D%E7%AB%AF%E6%BC%94%E8%BF%9B%E5%8F%B2)里引用了你《Web 开发简史与运行机制 》章节里的内容，文章最后加入了你的文章链接，希望能得到你的允许，如果不方便引用的话，稍后我会删除文章中对应的内容。
祝，生活愉快～

**Comment by wxyyxc1992** [comment]
好的，非常感谢，木有问题~
